/** <module> The M8c gate: Logical English for LPS

    Every `.le` under examples/lps/ is translated to LPS internal syntax and
    compared, term by term and up to variable renaming (`variant/2`), with the
    `.expected.lpsw` file beside it.

	./myswipl.sh -q -g "consult('testing/lps_test.pl')" -g "lps_test:main" -t halt

    and, to re-record the expectations after a deliberate change:

	./myswipl.sh -q -g "consult('testing/lps_test.pl')" -g "lps_test:record" -t halt

    `record` is for when the *language* changes, not for when a test goes red.
    An expectation regenerated from the code it is meant to check is not a
    test, so read the diff before committing one.
*/

:- module(lps_test, [main/0, record/0, translate/2]).

:- use_module(library(lists)).
:- use_module(library(apply)).
:- use_module('../le_lps').

lps_dir('examples/lps').

programs(Files) :-
	lps_dir(Dir),
	atom_concat(Dir, '/*.le', Pattern),
	expand_file_name(Pattern, Files0),
	sort(Files0, Files).

expected_file(LE, Expected) :-
	atom_concat(Base, '.le', LE),
	atom_concat(Base, '.expected.lpsw', Expected).

%!  translate(+File, -Terms) is semidet.
translate(File, Terms) :-
	le_lps:le_lps_file(File, Text, _Prov, Issues),
	\+ ( member(le_lps_issue(error, _, _, _, _), Issues) ),
	Text \== "",
	text_terms(Text, Terms).

text_terms(Text, Terms) :-
	setup_call_cleanup(open_string(Text, In), read_all(In, Terms), close(In)).

read_all(In, Terms) :-
	read_term(In, T, [module(lps_test)]),
	(   T == end_of_file
	->  Terms = []
	;   Terms = [T|Rest], read_all(In, Rest)
	).

		 /*******************************
		 *	     the gate		*
		 *******************************/

main :-
	programs(Files),
	foldl(check, Files, 0-0, Pass-Fail),
	Total is Pass + Fail,
	format('~nM8c: ~w of ~w programs match their expectation~n', [Pass, Total]),
	( Fail =:= 0 -> true ; halt(1) ).

check(File, P0-F0, P-F) :-
	file_base_name(File, Base),
	(   \+ translate(File, _)
	->  format('  FAIL  ~w — did not translate~n', [Base]), P = P0, F is F0 + 1
	;   translate(File, Terms),
	    expected_file(File, Exp),
	    (   \+ exists_file(Exp)
	    ->  format('  FAIL  ~w — no expectation recorded~n', [Base]),
		P = P0, F is F0 + 1
	    ;   read_expected(Exp, Want),
		(   terms_match(Want, Terms, Report)
		->  format('  ok    ~w (~w terms)~n', [Base, Report]),
		    P is P0 + 1, F = F0
		;   format('  FAIL  ~w~n', [Base]),
		    report_diff(Want, Terms),
		    P = P0, F is F0 + 1
		)
	    )
	).

read_expected(File, Terms) :-
	setup_call_cleanup(
	    open(File, read, In, [encoding(utf8)]),
	    read_all(In, Terms),
	    close(In)).

%   Term by term, in order, up to variable renaming. Order matters: the
%   emitter's families are deliberately ordered (settings, declarations,
%   initial state, then the rules in source order), and a program whose terms
%   came out in a different order is a program that changed.
terms_match(Want, Got, Count) :-
	length(Want, N), length(Got, N),
	maplist([A,B]>>variant(A, B), Want, Got),
	Count = N.

report_diff(Want, Got) :-
	length(Want, NW), length(Got, NG),
	( NW =:= NG -> true ; format('        ~w terms expected, ~w produced~n', [NW, NG]) ),
	first_difference(Want, Got, 1).

first_difference([], [], _) :- !.
first_difference([], [G|_], N) :- !, format('        term ~w: unexpected ~q~n', [N, G]).
first_difference([W|_], [], N) :- !, format('        term ~w: missing ~q~n', [N, W]).
first_difference([W|Ws], [G|Gs], N) :-
	(   variant(W, G)
	->  N1 is N + 1, first_difference(Ws, Gs, N1)
	;   format('        term ~w~n          expected: ~q~n          produced: ~q~n', [N, W, G])
	).

		 /*******************************
		 *	    recording		*
		 *******************************/

record :-
	programs(Files),
	forall(member(F, Files), record_one(F)).

record_one(File) :-
	file_base_name(File, Base),
	(   le_lps:le_lps_file(File, Text, _, Issues),
	    Text \== "",
	    \+ member(le_lps_issue(error, _, _, _, _), Issues)
	->  expected_file(File, Exp),
	    setup_call_cleanup(
		open(Exp, write, S, [encoding(utf8)]),
		( format(S, '% Generated by testing/lps_test.pl from ~w.~n', [Base]),
		  format(S, '% The internal syntax le_lps.pl must produce for it (M8c).~n~n', []),
		  write(S, Text) ),
		close(S)),
	    format('recorded ~w~n', [Base])
	;   format('SKIPPED  ~w — does not translate~n', [Base])
	).
